application:
  name: backend
  project: bloomly
  publicly_accessible: true
  dockerfile: backend/Dockerfile
routers:
  - name: api
    routes:
      - application_name: backend
        paths:
          - /api